name: build
on: push
jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: windows-latest, target: windows }
          - { os: ubuntu-18.04, target: linux }
          - { os: macos-latest, target: macos }
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/master
          submodules: recursive

      - uses: actboy168/setup-luamake@master

      - name: Running `luamake`
        run: luamake

      - uses: actions/upload-artifact@v2
        with:
          name: lua-language-server-${{ matrix.job.target }}
          path: bin
